// <auto-generated />
using System;
using CODE_FIRST_Fogliano_Eloy.MODEL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CODE_FIRST_Fogliano_Eloy.Migrations
{
    [DbContext(typeof(ClassicModelsDBContext))]
    [Migration("20240228232423_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Customer", b =>
                {
                    b.Property<int>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactLastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("SalesRepEmployeeNumber")
                        .HasColumnType("int(11)");

                    b.Property<int>("SalesRepKey")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("CustomerNumber");

                    b.HasIndex("SalesRepEmployeeNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Employee", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OfficeKey")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("ReportsToEmployeeNumber")
                        .HasColumnType("int(11)");

                    b.Property<int>("ReportsToKey")
                        .HasColumnType("int");

                    b.HasKey("EmployeeNumber");

                    b.HasIndex("OfficeKey");

                    b.HasIndex("ReportsToEmployeeNumber");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Office", b =>
                {
                    b.Property<string>("OfficeCode")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("OfficeCode");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Order", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("OrderNumber");

                    b.HasIndex("CustomerKey");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.OrderDetail", b =>
                {
                    b.Property<int>("OrderNumber")
                        .HasColumnType("int(11)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("varchar(15)");

                    b.Property<short>("OrderLineNumber")
                        .HasColumnType("smallint(6)");

                    b.Property<decimal>("PriceEach")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int(11)");

                    b.HasKey("OrderNumber", "ProductCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Payment", b =>
                {
                    b.Property<int>("CustomerNumber")
                        .HasColumnType("int");

                    b.Property<string>("CheckNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date");

                    b.HasKey("CustomerNumber", "CheckNumber");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MSRP")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductLineId")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("ProductScale")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProductVendor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<short>("QuantityInStock")
                        .HasColumnType("smallint");

                    b.HasKey("ProductCode");

                    b.HasIndex("ProductLineId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.ProductLine", b =>
                {
                    b.Property<string>("productLine")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("HtmlDescription")
                        .IsRequired()
                        .HasColumnType("mediumtext");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<string>("TextDescription")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.HasKey("productLine");

                    b.ToTable("ProductLines");
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Customer", b =>
                {
                    b.HasOne("CODE_FIRST_Fogliano_Eloy.MODEL.Employee", "SalesRep")
                        .WithMany("Customers")
                        .HasForeignKey("SalesRepEmployeeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Employee", b =>
                {
                    b.HasOne("CODE_FIRST_Fogliano_Eloy.MODEL.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_FIRST_Fogliano_Eloy.MODEL.Employee", "ReportsTo")
                        .WithMany("Reports")
                        .HasForeignKey("ReportsToEmployeeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Order", b =>
                {
                    b.HasOne("CODE_FIRST_Fogliano_Eloy.MODEL.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.OrderDetail", b =>
                {
                    b.HasOne("CODE_FIRST_Fogliano_Eloy.MODEL.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CODE_FIRST_Fogliano_Eloy.MODEL.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Payment", b =>
                {
                    b.HasOne("CODE_FIRST_Fogliano_Eloy.MODEL.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CODE_FIRST_Fogliano_Eloy.MODEL.Product", b =>
                {
                    b.HasOne("CODE_FIRST_Fogliano_Eloy.MODEL.ProductLine", "ProductLine")
                        .WithMany("Products")
                        .HasForeignKey("ProductLineId");
                });
#pragma warning restore 612, 618
        }
    }
}
